{% set name = "python-lambda-4dn" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9661582b571a0478f7701c22a7edcb871e7bf21f20df04aeb63b2ad953f122b8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  build:
    - pip
  host:
    - boto3 >=1.7.42
    - botocore >=1.10.42
    - docutils >=0.14
    - python >=3.5
    - pip
  run:
    - pip
    - boto3 >=1.7.42
    - botocore >=1.10.42
    - docutils >=0.14
    - python >=3.5

test:
  imports:
    - aws_lambda
    - aws_lambda.examples

about:
  home: "https://github.com/4dn-dcic/python-lambda"
  license: "ISC (ISCL)"
  license_family: "OTHER"
  license_file: "LICENSE"
  summary: "FORKED for 4dn-dcic. Use to package and deploy lambda functions."
  doc_url: "https://github.com/4dn-dcic/python-lambda"

extra:
  recipe-maintainers:
    - soolee
